
on: [push, pull_request]

name: Build on push

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.73
          components: rustfmt, clippy
      - name: Build
        run: cargo build
      - name: Run clippy and fail if any warnings
        run: cargo clippy -- -D warnings
      - name: Run tests
        run: cargo test
