name: Build release

# TODO: Add targets for arm and container image build
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master


jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: cargo build --release --locked
      - name: Bump version and push tag/create release point
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          INITIAL_VERSION: 0.2.1
        id: bump_version
      - name: "Create GitHub Release"
        uses: actions/create-release@v1 # https://github.com/actions/create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.bump_version.outputs.tag}}
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/reqsink
          asset_name: reqsink-linux-amd64
          tag: ${{steps.bump_version.outputs.tag}}
          overwrite: true
